crossplane-contrib/provider-azure

Gopkg.lock
Gopkg.toml
config/crd/azure.crossplane.io_providers.yaml
config/crd/azure.crossplane.io_resourcegroups.yaml
config/crd/cache.azure.crossplane.io_redis.yaml
config/crd/cache.azure.crossplane.io_redisclasses.yaml
config/crd/compute.azure.crossplane.io_aksclusterclasses.yaml
config/crd/compute.azure.crossplane.io_aksclusters.yaml
config/crd/database.azure.crossplane.io_mysqlservers.yaml
config/crd/database.azure.crossplane.io_postgresqlservers.yaml
config/crd/database.azure.crossplane.io_sqlserverclasses.yaml
config/crd/storage.azure.crossplane.io_accountclasses.yaml
config/crd/storage.azure.crossplane.io_accounts.yaml
config/crd/storage.azure.crossplane.io_containerclasses.yaml
config/crd/storage.azure.crossplane.io_containers.yaml

This PR updates our usage of controller-tools to the upstream now that https://github.com/kubernetes-sigs/controller-tools/pull/303 has been merged.
I have:

Use upstream controller-tools

---

Jenkinsfile

This PR is attempting to get official builds running on Jenkins in a new stack-azure pipeline: https://jenkinsci.upbound.io/blue/organizations/jenkins/crossplane%2Fstack-azure/activity
We'll want to have the same full functionality that the main crossplane repo has, such as SonarCloud checks and Integration tests, but I'm stripping the Jenkinsfile down for now just to get the build pipeline off the ground.

Get official builds running for stack-azure repo

---

cluster/images/stack-azure/Dockerfile

Typo in Dockerfile entrypoint was causing container to crash when pulling `master` from registry.
I have:

fix Dockerfile entrypoint typo

---

Makefile

Signed-off-by: soorena776 <javad@upbound.io>
I have:

    Move manifests target to `kubebuilder.mk` in build submodule

---

go.mod
go.sum

This commit is the result of running:
```
go get github.com/crossplane/crossplane
go get github.com/crossplane/crossplane-runtime
make reviewable
```
My assumption is the big red diff is because those projects are now using Go modules, and thus we don't need to handle their dependencies indirectly?
I have:

Bump crossplane and crossplane-runtime dependencies

---

apis/storage/v1alpha2/test/account.go
pkg/controller/cache/redis_test.go
pkg/controller/database/mysqlservervirtualnetworkrule/managed_test.go
pkg/controller/database/postgresqlservervirtualnetworkrule/managed_test.go
pkg/controller/network/subnet/managed_test.go
pkg/controller/network/virtualnetwork/managed.go
pkg/controller/network/virtualnetwork/managed_test.go
pkg/controller/resourcegroup/resourcegroup_test.go
pkg/controller/storage/account/account_test.go

Thanks to @turkenh who discovered this bug!
The main fix here is that the virtual network managed controller was not getting the provider secret ref namespace correctly (see first commit). Second update is changing all managed controller tests to not assume that provider has namespace / managed resource has namespace. I will check other stacks to see if these updates are needed.
I have:

VNet managed controller provider ref bugfix

---

go.mod
go.sum
pkg/controller/cache/claim.go
pkg/controller/compute/claim.go
pkg/controller/storage/account/claim.go
pkg/controller/storage/container/claim.go

Update to `v0.2.0` of `crossplane-runtime` includes the following fixes:
- https://github.com/crossplaneio/crossplane-runtime/issues/63
- https://github.com/crossplaneio/crossplane-runtime/issues/62
- https://github.com/crossplaneio/crossplane-runtime/issues/57
I have:

back-port fixes for v0.2.1

---

cluster/local/integration_tests.sh
config/stack/manifests/app.yaml
config/stack/manifests/install.yaml
config/stack/manifests/resources/accountclass.resource.yaml
config/stack/manifests/resources/aksclusterclass.resource.yaml
config/stack/manifests/resources/containerclass.resource.yaml
config/stack/manifests/resources/redisclass.resource.yaml
config/stack/manifests/resources/sqlserverclass.resource.yaml

This PR bumps the internal stack references to the soon to be released version of v0.4.0, as well as updating the stack resource readmes to reference the soon to be released crossplane.io docs version 0.6.
I have:
[`app.yaml`]: https://github.com/crossplaneio/stack-gcp/blob/master/config/stack/manifests/app.yaml

Bump stack-azure version refs to v0.4.0

---

pkg/clients/graph.go
pkg/controller/compute/akscluster.go

https://github.com/crossplaneio/crossplane-runtime/issues/1
Per the above issue the util package is deprecated. As best I can tell the AKS cluster controller is the only user of this retry setting, so suggest we move it to where it's used.
I have:

Rehome crossplane-runtime util functions

---

README.md
config/stack/manifests/app.yaml
config/stack/manifests/resources/accountclass.resource.yaml
config/stack/manifests/resources/aksclusterclass.resource.yaml
config/stack/manifests/resources/containerclass.resource.yaml
config/stack/manifests/resources/redisclass.resource.yaml
config/stack/manifests/resources/sqlserverclass.resource.yaml

The `portable resource abstractions` link no longer exists (this change was already made in release). The docs api references no longer exist on `master` and the `v0.7` release was the last one in which they did. These changes also remove almost all updates required in our branch prep PRs.
I have:

Remove missing docs links and minimize release branch prep

---

apis/v1alpha3/types.go
config/crd/azure.crossplane.io_resourcegroups.yaml
pkg/clients/resourcegroup/fake/fake.go
pkg/controller/resourcegroup/resourcegroup.go
pkg/controller/resourcegroup/resourcegroup_test.go

It seems that calling delete on a resource group extends the time required to delete the group; presumably some deletion process is restarted? This results in the resource group never actually being deleted.
I have:

Don't delete resource groups that are already deleting

---

cluster/images/provider-azure/Dockerfile

This updates the provider-gcp Dockerfile to run as non-root
as the Crossplane stack manager will refuse to run containers
as root by default per https://github.com/crossplane/crossplane/pull/1444
See https://github.com/crossplane/provider-gcp/pull/223 for testing
I have:

Run provider-azure controllers as non-root

---

pkg/clients/database/mysql.go
pkg/clients/database/postgresql.go
pkg/controller/database/mysqlserver/managed.go
pkg/controller/database/mysqlserver/managed_test.go
pkg/controller/database/postgresqlserver/managed.go
pkg/controller/database/postgresqlserver/managed_test.go

Azure MySQLServer API allows calling `Create` multiple times and it returns `NotFound` until the server is created successfully. We can't call `Create` multiple times until we see the resource because it'd generate a different password but we don't know whether a creation is in progress either. How we worked around this has been checking the name availability of the MySQL server; if it's not available then it's in creation. But this is not a viable solution since we never return error if in fact a completely different MySQL Server exists with the same name but in a different resource group, meaning we can't take over control but we don't return an error either. What happens is that `Update` fails because it cannot find that SQL Server in that specific `ResourceGroup` like the following: …

Fix already exists error in SQL resources

---

apis/storage/v1alpha3/test/account.go
apis/storage/v1alpha3/types.go
examples/cache/redis.yaml
examples/compute/akscluster.yaml
examples/database/cosmosdbaccount.yaml
examples/database/mysqlserver.yaml
examples/database/postgresqlserver.yaml
examples/network/subnet.yaml
examples/network/virtualnetwork.yaml
examples/storage/account.yaml
examples/storage/container.yaml
package/crds/storage.azure.crossplane.io_accounts.yaml
pkg/controller/storage/container/container_test.go

Removes all references to reclaimPolicy, which has been replaced by deletionPolicy, and resource classes, which have been removed.
xref crossplane/crossplane#1781
I have:
`make generate`
`make reviewable`

Remove references to reclaim policy and resource classes

---

apis/database/v1beta1/sql_types.go
apis/database/v1beta1/zz_generated.deepcopy.go
package/crds/database.azure.crossplane.io_mysqlservers.yaml
package/crds/database.azure.crossplane.io_postgresqlservers.yaml
pkg/clients/database/mysql.go
pkg/clients/database/mysql_test.go
pkg/clients/database/postgresql.go
pkg/clients/database/postgresql_test.go
pkg/clients/database/util.go

Fixes: #209
The duplication in the creation of the Azure API object is undesirable
but I can't see any way around it short of serialising back to JSON and
up again via the Azure API JSON decode path, which seems more fragile
than the typed code path this provides.
Signed-off-by: Robert Collins <robert.collins@cognite.com>
Fixes #209 
I have:
- [X ] Read and followed Crossplane's [contribution process].
- [X ] Run `make reviewable test` to ensure this PR is ready for review.
I haven't yet testing this against a live Azure cluster - as with the fix for 210, I'd love some guidance on how to connect a dev build directly to a cluster - if someone can step me through it on slack I can write it up as a doc fix.

Permit restoring mysql/postgresql DBs

---

pkg/clients/database/mysql.go
pkg/clients/database/mysql_test.go
pkg/clients/database/postgresql.go
pkg/clients/database/postgresql_test.go

https://github.com/crossplane/provider-azure/pull/214 managed to sneak some broken unit tests into master (I think due to some quirk of the detect-noop job). There were some cases in which our tests expected us to send an empty-string CreateMode to the Azure API whereas in practice we were sending `Default`. I believe we always want to send one of the valid create modes (i.e. we should never try to send the empty string).
CC @rbtcollins 
I have:

Always supply the Azure API with a SQL server create mode

---

cmd/provider/main.go
go.mod
go.sum
pkg/controller/azure.go
pkg/controller/cache/redis.go
pkg/controller/compute/managed.go
pkg/controller/config/config.go
pkg/controller/database/cosmosdb/managed.go
pkg/controller/database/mysqlserver/managed.go
pkg/controller/database/mysqlserverfirewallrule/managed.go
pkg/controller/database/mysqlservervirtualnetworkrule/managed.go
pkg/controller/database/postgresqlserver/managed.go
pkg/controller/database/postgresqlserverfirewallrule/managed.go
pkg/controller/database/postgresqlservervirtualnetworkrule/managed.go
pkg/controller/network/subnet/managed.go
pkg/controller/network/virtualnetwork/managed.go
pkg/controller/resourcegroup/resourcegroup.go
pkg/controller/storage/account/account.go
pkg/controller/storage/container/container.go

Updates all controllers to use updated managed reconciler and a max of
rate limiter that accepts the provider-level token bucket limiter and a
per-item exponential backoff limiter with base delay of 1s and max delay
of 60s.
I have:

Update all controllers to use default managed rate limiter

---

apis/storage/v1alpha3/account.go
apis/storage/v1alpha3/account_test.go
package/crds/storage.azure.crossplane.io_accounts.yaml

Signed-off-by: craigbryson <37695591+craigbryson@users.noreply.github.com>
Fixes #232 
Removes options for table and queue encryption since these cannot be modified. Accounts now reconcile successfully.
There are some potentially breaking changes to CRDs (removal) not sure how best to handle these?
I have:
- [ X] Read and followed Crossplane's [contribution process].
- [ X] Run `make reviewable test` to ensure this PR is ready for review.
Tested locally provisioning a storage account as per the issue - account now reconciles successfully. No failed API operations are shown in the activity log

Remove Queue and Table related encryption operations

---

pkg/clients/database/mysql.go
pkg/clients/database/postgresql.go

It reports difference in `IsUpToDate` because the local value is always empty while the remote one always has a value since it's an enum.
Fixes https://github.com/crossplane/provider-azure/issues/237
I have:
Manual test not necessary.

sql: late init enum fields

---

apis/compute/v1alpha3/types.go
package/crds/compute.azure.crossplane.io_aksclusters.yaml

While running crossplane conformance tests, I observed following failure:
```
=== RUN   TestPackage/DeploysConformantCRDs/AKSCluster
provider_test.go:436: version "v1alpha3" OpenAPI schema: -want, +got:
&v1.JSONSchemaProps{
... // 1 ignored and 25 identical fields
AnyOf: nil,
Not:   nil,
Properties: map[string]v1.JSONSchemaProps{
... // 2 identical entries
"metadata": {Type: "object"},
+ go-junit-report
"spec":     {Type: "object", Properties: {"deletionPolicy": {Type: "string", Enum: {{Raw: {0x22, 0x4f, 0x72, 0x70, ...}}, {Raw: {0x22, 0x44, 0x65, 0x6c, ...}}}}, "providerConfigRef": {Type: "object", Required: {"name"}, Properties: {"name": {Type: "string"}}}, "writeConnectionSecretToRef": {Type: "object", Required: {"name", "namespace"}, Properties: {"name": {Type: "string"}, "namespace": …
```

Mark status.endpoint as optional in AKSCluster

---

apis/network/v1alpha3/types.go
package/crds/network.azure.crossplane.io_subnets.yaml

Signed-off-by: Hasan Turken <turkenh@gmail.com>
Subnet does not have a `spec.location` and ready/synced not available in get output.
This PR changes from:
```
NAME               STATE      LOCATION   AGE
conformancetest1   Updating              6m41s
```
To:
```
NAME               READY   SYNCED   STATE      AGE
conformancetest1   False   True     Updating   7m22s
```
I have:
Create a subnet and run kubectl get.

Fix Print Columns for Subnet

---

pkg/clients/network/network.go
pkg/clients/network/network_test.go

When setting this property to False in the Crossplane VirtualNetwork CR,
the controller finds itself constantly reconciling actual and desired
state. This leads to a lot of instability when trying to create
resources in that VNET, as there is never any convergence.
Adding a few log messages in the provider, I observed that there was
always a mismatch between the EnableVMProtection property for the
desired object (pointer to a boolean value set to false) and the one
for the actual object obtained from the Azure SDK (which is nil).
So it seems that using FieldRequired for EnableVMProtection may not be
accurate, at least not with the version of the SDK currently used by
Crossplane.
Signed-off-by: Antonin Bas <abas@vmware.com>
I have:
Created Vnets with EnableVMProtection set to false and …

Remove FieldRequired for EnableVMProtection VNET property

---

.github/workflows/ci.yml
Makefile
cluster/local/integration_tests.sh
pkg/controller/database/postgresqlserver/managed.go

This PR proposes a fix for the wrong password in the generated connection secret issue discussed in #230. The proposed behavior is backwards-compatible and in case multiple `Creates` are called and if a connection secret is defined, we make sure that the password initially used to make the Azure PostgreSQLServer create call is reused, effectively preventing multiple erroneous password generations and the issue described in #230. 
Fixes #230 
I have:
I have written a test script that does the following in a loop:
1. Apply the claim defined below to provision a PostgreSQLServer
2. Waits until the PostgreSQLServer MR becomes ready
3. Invokes `az postgres server firewall-rule create` against this newly provisioned instance to allow connections from my workstation
4. Invokes `psql` using the …

Read PostgreSQL admin password from connection secret

---

cmd/provider/main.go
pkg/controller/azure.go
pkg/controller/cache/redis.go
pkg/controller/compute/managed.go
pkg/controller/database/cosmosdb/managed.go
pkg/controller/database/mysqlserver/managed.go
pkg/controller/database/mysqlserverfirewallrule/managed.go
pkg/controller/database/mysqlservervirtualnetworkrule/managed.go
pkg/controller/database/postgresqlserver/managed.go
pkg/controller/database/postgresqlserverfirewallrule/managed.go
pkg/controller/database/postgresqlservervirtualnetworkrule/managed.go
pkg/controller/network/subnet/managed.go
pkg/controller/network/virtualnetwork/managed.go
pkg/controller/resourcegroup/resourcegroup.go
pkg/controller/storage/account/account.go
pkg/controller/storage/account/account_test.go
pkg/controller/storage/container/container.go
pkg/controller/storage/container/container_test.go

Adds a `--poll-interval` flag to provider, which is passed to all controllers to set their polling interval in the reconciliation happy path.
*Note to reviewers: these changes are almost entirely find and replace.*
xref https://github.com/crossplane/crossplane-runtime/issues/253
Fixes #282 
I have:
See https://github.com/crossplane/provider-aws/pull/741 for testing steps.

Add global poll interval flag

---

apis/storage/v1alpha3/test/container.go
pkg/controller/storage/container/container.go
pkg/controller/storage/container/container_test.go

Fixes a panic in the storage container controller that used the provider
reference name in the error when we are unable to get the storage
account that serves as this type's provider. The ProviderReference may
be nil in the case that the newer ProviderConfigReference is used.
Fixes https://github.com/crossplane/provider-azure/issues/248
I have:
I have not tested this change extensively, but I have a high degree of confidence in the fix given the observed stack trace on panic:
```
goroutine 692 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/home/runner/work/provider-azure/provider-azure/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/runtime/runtime.go:55 +0x109
panic(0x197c8e0, 0x2993560) …
```

Fix panic when returning error with provider reference name

---

examples/database/postgresqlserver.yaml
pkg/clients/database/mysql.go
pkg/clients/database/postgresql.go

Signed-off-by: Sergen Yalçın <yalcinsergen97@gmail.com>
Fixes #307 
This PR solves the problem that `IsPostgreSQLUpToDate` function always returns false. When the value of `sslEnforcement` is `Disabled`, the `minimalTlsVersion` mismatch is ignored.
I have:
- A PostgreSqlServer was provisioned by using example manifest (value of `sslEnforcement` is `Disabled`). Then I observed that, the `IsPostgreSQLUpToDate` returned true despite there is a mismatch between the values of `minimalTlsVersion`.
- A PostgreSqlServer was provisioned by using example manifest (value of `sslEnforcement` is `Enabled`, value of `minimalTlsVersion` is `TLS1_2`). Then I observed that, cloud resource created with proper values and `IsPostgreSQLUpToDate` did not return false.
[contribution process]: …

Ignore minimalTlsVersion mismatch when the sslEnforcement is disabled

---

apis/compute/v1alpha3/types.go
package/crds/compute.azure.crossplane.io_aksclusters.yaml

Fixes doc string typos in the subnet referencer fields of the `AKSCluster` MR.
I have:
Ran `make generate` to observe doc string changes.

Fix AKSCluster doc comment typo

---

pkg/clients/compute/aks.go
pkg/controller/compute/managed.go
pkg/controller/compute/managed_test.go

Fixes #298
This PR proposes a change in the AKSCluster's reconciler where we reuse the graph Application's password credential across reconciliations instead of regenerating a brand new password each time.
With this PR, we also change the scheme of the associated graph Application's App ID URI from `https` to `api`. See [here](https://github.com/crossplane/provider-azure/issues/298#issuecomment-972550233) for a detailed account on this matter.
I have:
Successfully provisioned an AKSCluster in 5 of the 5 trials.

Reuse generated password for AKSCluster's Application

---

pkg/clients/network/network.go

This PR fixes the nil pointer issue for the PublicIPAddress resource. When IPConfiguration field is not nil, we need to check whether the IPConfigurationPropertiesFormat (embedded) is nil because we are trying to access the fields of the embedded struct. For example; `PrivateIPAllocationMethod`, `PrivateIPAddress`, `ProvisioningState`.
I have:
This PR was tested by filling manually the IPConfiguration field. Then the nil pointer issue was not observed.

Add nil check for IPConfigurationPropertiesFormat

---

.github/workflows/ci.yml
.github/workflows/promote.yml
Makefile
package/crossplane.yaml

Updates package source to point to the crossplane-contrib GitHub org.
Updates Makefile to push to crossplane-contrib on Upbound Marketplace
and crossplanecontrib on DockerHub.
Updates all GitHub workflows to use the crossplane-contrib Docker user.
I have:
Verified these updates work correctly in GCP and AWS providers.

Update to push to crossplane-contrib org
