crossplane-contrib/provider-azure

Gopkg.lock, config/crd/azure.crossplane.io_resourcegroups.yaml, config/crd/cache.azure.crossplane.io_redis.yaml, config/crd/cache.azure.crossplane.io_redisclasses.yaml, config/crd/compute.azure.crossplane.io_aksclusterclasses.yaml, config/crd/compute.azure.crossplane.io_aksclusters.yaml, config/crd/database.azure.crossplane.io_mysqlservers.yaml, config/crd/database.azure.crossplane.io_mysqlservervirtualnetworkrules.yaml, config/crd/database.azure.crossplane.io_postgresqlservers.yaml, config/crd/database.azure.crossplane.io_postgresqlservervirtualnetworkrules.yaml, config/crd/database.azure.crossplane.io_sqlserverclasses.yaml, config/crd/network.azure.crossplane.io_subnets.yaml, config/crd/network.azure.crossplane.io_virtualnetworks.yaml, config/crd/storage.azure.crossplane.io_accountclasses.yaml, config/crd/storage.azure.crossplane.io_accounts.yaml, config/crd/storage.azure.crossplane.io_containerclasses.yaml, config/crd/storage.azure.crossplane.io_containers.yaml, pkg/controller/azure/cache/claim.go, pkg/controller/azure/compute/claim.go, pkg/controller/azure/database/claim.go, pkg/controller/azure/storage/account/claim.go, pkg/controller/azure/storage/container/claim.go
See https://github.com/crossplaneio/crossplane-runtime/pull/24 for context. That PR must first be merged, and then this PR updated to depend on the latest build, before this PR can be merged.
Reviewers, please double check the kinds I've provided to each predicate to ensure they make sense; it's especially easy to mix up `FooGroupVersionKind` with `FooClassGroupVersionKind`.
I have:
=> Fix support for static provisioning

azure/apis/cache/v1alpha2/redis_types.go, azure/apis/compute/v1alpha2/types.go, azure/apis/database/v1alpha2/sql_types.go, azure/apis/network/v1alpha2/types.go, azure/apis/storage/v1alpha2/account.go, azure/apis/storage/v1alpha2/types.go, azure/apis/storage/v1alpha2/types_test.go, azure/apis/v1alpha2/doc.go, azure/apis/v1alpha2/register.go, azure/apis/v1alpha2/types.go, config/crd/azure.crossplane.io_providers.yaml, config/crd/azure.crossplane.io_resourcegroups.yaml, config/crd/cache.azure.crossplane.io_redis.yaml, config/crd/cache.azure.crossplane.io_redisclasses.yaml, config/crd/compute.azure.crossplane.io_aksclusterclasses.yaml, config/crd/compute.azure.crossplane.io_aksclusters.yaml, config/crd/database.azure.crossplane.io_mysqlservers.yaml, config/crd/database.azure.crossplane.io_mysqlservervirtualnetworkrules.yaml, config/crd/database.azure.crossplane.io_postgresqlservers.yaml, config/crd/database.azure.crossplane.io_postgresqlservervirtualnetworkrules.yaml, config/crd/database.azure.crossplane.io_sqlserverclasses.yaml, config/crd/network.azure.crossplane.io_subnets.yaml, config/crd/network.azure.crossplane.io_virtualnetworks.yaml, config/crd/storage.azure.crossplane.io_accountclasses.yaml, config/crd/storage.azure.crossplane.io_accounts.yaml, config/crd/storage.azure.crossplane.io_containerclasses.yaml, config/crd/storage.azure.crossplane.io_containers.yaml
This documentation is used to generate our user facing documentation, both in CRDs and on the website. I've edited it for tone, and to generally make sense where it did not.
I have:
=> Update GoDoc for Azure.

azure/apis/cache/v1alpha2/redis_types.go, azure/apis/compute/v1alpha2/types.go, azure/apis/database/v1alpha2/sql_types.go, azure/apis/storage/v1alpha2/types.go, config/crd/cache.azure.crossplane.io_redisclasses.yaml, config/crd/compute.azure.crossplane.io_aksclusterclasses.yaml, config/crd/database.azure.crossplane.io_sqlserverclasses.yaml, config/crd/storage.azure.crossplane.io_accountclasses.yaml, config/crd/storage.azure.crossplane.io_containerclasses.yaml
They're not very useful without them.
I have:
=> Require resource classes to have spec templates

Gopkg.lock, pkg/controller/azure/cache/claim.go, pkg/controller/azure/compute/claim.go, pkg/controller/azure/database/claim.go, pkg/controller/azure/storage/account/claim.go, pkg/controller/azure/storage/container/claim.go
=> claim predicates: remove hasdirectclassreferencekind in favor of ismanagedkind

Jenkinsfile, Makefile, cluster/local/helm-rbac.yaml, cluster/local/integration_tests.sh
Fixes crossplaneio/crossplane#759
This initial implementation just installs the stacks and makes sure its pods are running. In the future, we may want to actually create some custom resources.
I have:
=> Implement Integration Tests

pkg/clients/compute/aks.go
Fix to issue experienced in https://github.com/crossplaneio/stack-azure/pull/35#issuecomment-544739712
I have:
=> aks: dont set vnetsubnetid if not existing

go.mod, go.sum, pkg/controller/storage/account/claim.go, pkg/controller/storage/container/claim.go
See https://github.com/crossplaneio/crossplane-runtime/pull/55
I have:
=> Update crossplane-runtime to fix static provisioning

config/stack/manifests/resources/account.ui-schema.yaml, config/stack/manifests/resources/accountclass.ui-schema.yaml, config/stack/manifests/resources/akscluster.ui-schema.yaml, config/stack/manifests/resources/aksclusterclass.ui-schema.yaml, config/stack/manifests/resources/container.ui-schema.yaml, config/stack/manifests/resources/containerclass.ui-schema.yaml, config/stack/manifests/resources/mysqlserver.ui-schema.yaml, config/stack/manifests/resources/mysqlservervirtualnetworkrule.ui-schema.yaml, config/stack/manifests/resources/postgresqlserver.ui-schema.yaml, config/stack/manifests/resources/postgresqlservervirtualnetworkrule.ui-schema.yaml, config/stack/manifests/resources/provider.ui-schema.yaml, config/stack/manifests/resources/redis.ui-schema.yaml, config/stack/manifests/resources/redisclass.ui-schema.yaml, config/stack/manifests/resources/resourcegroup.ui-schema.yaml, config/stack/manifests/resources/sqlserverclass.ui-schema.yaml, config/stack/manifests/resources/subnet.ui-schema.yaml, config/stack/manifests/resources/virtualnetwork.ui-schema.yaml, config/stack/samples/install.stack.yaml, config/stack/samples/local.install.stack.yaml
Per the [Stack UI Schema Status Spec](https://github.com/crossplaneio/crossplane/blob/4cf353351fc7fa3d58210fc790a6b30e7f74309b/design/one-pager-stack-status-spec.md#design), resources provided by a Stack may report to UI tools the status of the provisioned resource.
One approach to hint the UI, it a so-called [fallback option](https://github.com/crossplaneio/crossplane/blob/4cf353351fc7fa3d58210fc790a6b30e7f74309b/design/one-pager-stack-status-spec.md#fallback-option).  This approach defers to a "READY" additionalPrinterColumn defined in the CRD. Use of this approach would not require a `ui-schema.yaml` but resources in this Stack do not report the necessary READY column.
Because this Stack takes advantage of the Crossplane Runtime's Conditioned Status pattern, there is a predictable path …
=> stacks: report Ready status for all managed types using ui-schema

apis/cache/v1alpha3/redis_types.go, config/crd/cache.azure.crossplane.io_redis.yaml
Missing `STATE` and `STATUS` was not pointing to `BindingPhase`.
I have:
=> printer column: fix redis status and state

go.mod, go.sum, pkg/controller/cache/claim.go, pkg/controller/compute/claim.go, pkg/controller/storage/account/claim.go, pkg/controller/storage/container/claim.go
https://github.com/crossplaneio/crossplane-runtime/releases/tag/v0.2.0
This update fixes several and requires a few API changes per the above release notes.
I have:
=> Update to crossplane-runtime v0.2.0

Jenkinsfile, Makefile, config/crd/cache.azure.crossplane.io_redis.yaml, config/crd/cache.azure.crossplane.io_redisclasses.yaml
Causes CI to check for dirty go modules and fail if so.
I have:
=> Check for dirty go modules in CI

go.mod, go.sum, pkg/controller/compute/akscluster.go
Implements https://github.com/crossplaneio/crossplane/issues/861 for AKS clusters.
I have:
=> aks: publish raw kubeconfig in connection details secret

cluster/local/integration_tests.sh, config/stack/manifests/app.yaml, config/stack/manifests/install.yaml, config/stack/manifests/resources/accountclass.resource.yaml, config/stack/manifests/resources/aksclusterclass.resource.yaml, config/stack/manifests/resources/containerclass.resource.yaml, config/stack/manifests/resources/redisclass.resource.yaml, config/stack/manifests/resources/sqlserverclass.resource.yaml
Per https://github.com/crossplaneio/crossplane/blob/1fb67d0/docs/release/release-process.md#stack-release-process
I have:
=> Prepare to release v0.3.0

config/crd/azure.crossplane.io_resourcegroups.yaml, config/crd/cache.azure.crossplane.io_redis.yaml, config/crd/cache.azure.crossplane.io_redisclasses.yaml, config/crd/compute.azure.crossplane.io_aksclusterclasses.yaml, config/crd/compute.azure.crossplane.io_aksclusters.yaml, config/crd/database.azure.crossplane.io_mysqlservers.yaml, config/crd/database.azure.crossplane.io_mysqlservervirtualnetworkrules.yaml, config/crd/database.azure.crossplane.io_postgresqlservers.yaml, config/crd/database.azure.crossplane.io_postgresqlservervirtualnetworkrules.yaml, config/crd/database.azure.crossplane.io_sqlserverclasses.yaml, config/crd/network.azure.crossplane.io_subnets.yaml, config/crd/network.azure.crossplane.io_virtualnetworks.yaml, config/crd/storage.azure.crossplane.io_accountclasses.yaml, config/crd/storage.azure.crossplane.io_accounts.yaml, config/crd/storage.azure.crossplane.io_containerclasses.yaml, config/crd/storage.azure.crossplane.io_containers.yaml, go.mod, go.sum, pkg/controller/cache/claim.go, pkg/controller/compute/claim.go, pkg/controller/database/mysqlserver/claim.go, pkg/controller/database/postgresqlserver/claim.go, pkg/controller/storage/account/claim.go, pkg/controller/storage/account/claim_test.go, pkg/controller/storage/container/claim.go
=> Bump crossplane-runtime for updated ReclaimPolicy semantics

cluster/local/integration_tests.sh, config/crd/azure.crossplane.io_resourcegroups.yaml, config/crd/cache.azure.crossplane.io_redis.yaml, config/crd/cache.azure.crossplane.io_redisclasses.yaml, config/crd/compute.azure.crossplane.io_aksclusterclasses.yaml, config/crd/compute.azure.crossplane.io_aksclusters.yaml, config/crd/database.azure.crossplane.io_mysqlservers.yaml, config/crd/database.azure.crossplane.io_mysqlservervirtualnetworkrules.yaml, config/crd/database.azure.crossplane.io_postgresqlservers.yaml, config/crd/database.azure.crossplane.io_postgresqlservervirtualnetworkrules.yaml, config/crd/database.azure.crossplane.io_sqlserverclasses.yaml, config/crd/network.azure.crossplane.io_subnets.yaml, config/crd/network.azure.crossplane.io_virtualnetworks.yaml, config/crd/storage.azure.crossplane.io_accountclasses.yaml, config/crd/storage.azure.crossplane.io_accounts.yaml, config/crd/storage.azure.crossplane.io_containerclasses.yaml, config/crd/storage.azure.crossplane.io_containers.yaml, config/stack/manifests/app.yaml, config/stack/manifests/install.yaml, go.mod, go.sum, pkg/controller/cache/claim.go, pkg/controller/compute/claim.go, pkg/controller/database/mysqlserver/claim.go, pkg/controller/database/postgresqlserver/claim.go, pkg/controller/storage/account/claim.go, pkg/controller/storage/account/claim_test.go, pkg/controller/storage/container/claim.go
=> Prep release 0.3.1

examples/azure-provider.yaml, examples/cache/rediscluster/resource-claim.yaml, examples/cache/rediscluster/resource-class.yaml, examples/compute/kubernetescluster/resource-claim.yaml, examples/compute/kubernetescluster/resource-class.yaml, examples/database/mysqlinstance/resource-claim.yaml, examples/database/mysqlinstance/resource-class.yaml, examples/database/postgresqlinstance/resource-claim.yaml, examples/database/postgresqlinstance/resource-class.yaml, examples/stack-azure.yaml, examples/storage/bucket/account-resource-class.yaml, examples/storage/bucket/container-resource-class.yaml, examples/storage/bucket/resource-claim.yaml
Same as https://github.com/crossplaneio/stack-gcp/pull/105/files
I have:
=> examples: move examples from crossplane repo

apis/cache/v1beta1/redis_types.go, apis/compute/v1alpha3/types.go, apis/database/v1alpha3/virtualnetworkrule.go, apis/database/v1beta1/sql_types.go, apis/network/v1alpha3/types.go, apis/storage/v1alpha3/types.go, apis/v1alpha3/types.go, config/crd/azure.crossplane.io_providers.yaml, config/crd/azure.crossplane.io_resourcegroups.yaml, config/crd/cache.azure.crossplane.io_redis.yaml, config/crd/cache.azure.crossplane.io_redisclasses.yaml, config/crd/compute.azure.crossplane.io_aksclusters.yaml, config/crd/database.azure.crossplane.io_mysqlservers.yaml, config/crd/database.azure.crossplane.io_mysqlservervirtualnetworkrules.yaml, config/crd/database.azure.crossplane.io_postgresqlservers.yaml, config/crd/database.azure.crossplane.io_postgresqlservervirtualnetworkrules.yaml, config/crd/database.azure.crossplane.io_sqlserverclasses.yaml, config/crd/network.azure.crossplane.io_subnets.yaml, config/crd/network.azure.crossplane.io_virtualnetworks.yaml, config/crd/storage.azure.crossplane.io_accounts.yaml, config/crd/storage.azure.crossplane.io_containers.yaml
Validates the `spec` and `forProvider` are present on all managed resources so that we don't hit nil pointer exceptions in controllers.
I have:
=> api: require spec and forProvider in all resources

config/stack/manifests/resources/account.ui-schema.yaml, config/stack/manifests/resources/accountclass.ui-schema.yaml, config/stack/manifests/resources/akscluster.ui-schema.yaml, config/stack/manifests/resources/aksclusterclass.ui-schema.yaml, config/stack/manifests/resources/container.ui-schema.yaml, config/stack/manifests/resources/containerclass.ui-schema.yaml, config/stack/manifests/resources/mysqlserver.ui-schema.yaml, config/stack/manifests/resources/mysqlservervirtualnetworkrule.ui-schema.yaml, config/stack/manifests/resources/postgresqlserver.ui-schema.yaml, config/stack/manifests/resources/postgresqlservervirtualnetworkrule.ui-schema.yaml, config/stack/manifests/resources/provider.ui-schema.yaml, config/stack/manifests/resources/redis.ui-schema.yaml, config/stack/manifests/resources/redisclass.ui-schema.yaml, config/stack/manifests/resources/resourcegroup.ui-schema.yaml, config/stack/manifests/resources/sqlserverclass.ui-schema.yaml, config/stack/manifests/resources/subnet.ui-schema.yaml, config/stack/manifests/resources/virtualnetwork.ui-schema.yaml
Per https://github.com/crossplaneio/crossplane/pull/1145
Signed-off-by: Steven Rathbauer <steven@rathpc.com>
=> Update resourceConditionPaths --> new printerColumns syntax

cluster/local/integration_tests.sh, config/stack/manifests/app.yaml, config/stack/manifests/install.yaml, config/stack/manifests/resources/accountclass.resource.yaml, config/stack/manifests/resources/aksclusterclass.resource.yaml, config/stack/manifests/resources/containerclass.resource.yaml, config/stack/manifests/resources/redisclass.resource.yaml, config/stack/manifests/resources/sqlserverclass.resource.yaml, examples/stack-azure.yaml
Bumps references to stack-azure to v0.5.0 and Crossplane to 0.7
I have:
=> v0.5.0: docs and references prep

apis/storage/v1alpha3/types.go
https://github.com/crossplaneio/crossplane-runtime/issues/1
This function and the util package it lives in are deprecated. They'll be replaced by the new crossplane.io/external-name annotation once we port this controller to the managed resource reconciler. For now I'd like to remove it from crossplane-runtime/pkg/util as it is only used by the bucket controllers.
I have:
[`app.yaml`]: https://github.com/crossplaneio/stack-gcp/blob/master/config/stack/manifests/app.yaml
[stack resources documentation]: …
=> Rehome deprecated ConditionalStringFormat from crossplane-runtime

apis/storage/v1alpha3/account.go, cmd/stack/main.go, go.mod, go.sum, pkg/controller/azure.go, pkg/controller/cache/claim.go, pkg/controller/cache/redis.go, pkg/controller/compute/akscluster.go, pkg/controller/compute/akscluster_test.go, pkg/controller/compute/claim.go, pkg/controller/compute/compute_suite_test.go, pkg/controller/compute/target.go, pkg/controller/database/mysqlserver/claim.go, pkg/controller/database/mysqlserver/managed.go, pkg/controller/database/mysqlservervirtualnetworkrule/managed.go, pkg/controller/database/postgresqlserver/claim.go, pkg/controller/database/postgresqlserver/managed.go, pkg/controller/database/postgresqlservervirtualnetworkrule/managed.go, pkg/controller/network/subnet/managed.go, pkg/controller/network/virtualnetwork/managed.go, pkg/controller/resourcegroup/resourcegroup.go, pkg/controller/resourcegroup/resourcegroup_test.go, pkg/controller/storage/account/account.go, pkg/controller/storage/account/account_test.go, pkg/controller/storage/account/claim.go, pkg/controller/storage/container/claim.go, pkg/controller/storage/container/container.go, pkg/controller/storage/container/container_test.go
https://github.com/crossplaneio/crossplane-runtime/pull/108
This commit updates all stack-aws controllers to use the logging and event recording functionality added in the above crossplane-runtime PR. Legacy controllers are minimally updated to avoid package scoped loggers.
I have:
=> Plumb up logging and event recording implementations

go.mod, go.sum, pkg/controller/database/mysqlserver/managed.go, pkg/controller/database/mysqlserver/managed_test.go, pkg/controller/database/postgresqlserver/managed.go, pkg/controller/database/postgresqlserver/managed_test.go
The former has been replaced by the latter.
I have:
=> Switch util.GeneratePassword to password.Generate

apis/cache/v1beta1/register.go, apis/compute/v1alpha3/register.go, apis/database/v1alpha3/register.go, apis/database/v1beta1/register.go, apis/network/v1alpha3/register.go, apis/storage/v1alpha3/register.go, apis/v1alpha3/register.go, go.mod, go.sum, pkg/controller/cache/claim.go, pkg/controller/cache/redis.go, pkg/controller/compute/akscluster.go, pkg/controller/compute/claim.go, pkg/controller/compute/target.go, pkg/controller/database/mysqlserver/claim.go, pkg/controller/database/mysqlserver/managed.go, pkg/controller/database/mysqlservervirtualnetworkrule/managed.go, pkg/controller/database/postgresqlserver/claim.go, pkg/controller/database/postgresqlserver/managed.go, pkg/controller/database/postgresqlservervirtualnetworkrule/managed.go, pkg/controller/network/subnet/managed.go, pkg/controller/network/virtualnetwork/managed.go, pkg/controller/resourcegroup/resourcegroup.go, pkg/controller/storage/account/account.go, pkg/controller/storage/account/claim.go, pkg/controller/storage/container/claim.go, pkg/controller/storage/container/container.go
Per https://github.com/crossplaneio/crossplane/issues/1254
I have:
=> Use GroupKind, not Kind, for controller names

cluster/local/integration_tests.sh, config/stack/manifests/app.yaml, config/stack/manifests/install.yaml, config/stack/manifests/resources/accountclass.resource.yaml, config/stack/manifests/resources/aksclusterclass.resource.yaml, config/stack/manifests/resources/containerclass.resource.yaml, config/stack/manifests/resources/redisclass.resource.yaml, config/stack/manifests/resources/sqlserverclass.resource.yaml, examples/stack-azure.yaml
Prep docs and references for `v0.6.0` release.
I have:
=> [v0.6.0]: prep docs and references

Jenkinsfile, README.md, config/stack/manifests/resources/accountclass.resource.yaml, config/stack/manifests/resources/aksclusterclass.resource.yaml, config/stack/manifests/resources/containerclass.resource.yaml, config/stack/manifests/resources/redisclass.resource.yaml, config/stack/manifests/resources/sqlserverclass.resource.yaml
Does as the tittle suggests.
I have:
[`app.yaml`]: https://github.com/crossplane/stack-azure/blob/master/config/stack/manifests/app.yaml
=> Fix remaining references to crossplaneio

README.md, cluster/local/integration_tests.sh, config/stack/manifests/app.yaml, config/stack/manifests/resources/accountclass.resource.yaml, config/stack/manifests/resources/aksclusterclass.resource.yaml, config/stack/manifests/resources/containerclass.resource.yaml, config/stack/manifests/resources/redisclass.resource.yaml, config/stack/manifests/resources/sqlserverclass.resource.yaml, examples/stack-azure.yaml
Prep docs and references for v0.7.0 release
I have:
=> [release-0.7] Prep docs and references for v0.7.0 release

cluster/local/integration_tests.sh, config/stack/manifests/resources/accountclass.resource.yaml, config/stack/manifests/resources/aksclusterclass.resource.yaml, config/stack/manifests/resources/containerclass.resource.yaml, config/stack/manifests/resources/redisclass.resource.yaml, config/stack/manifests/resources/sqlserverclass.resource.yaml, config/stack/samples/install.stack.yaml, examples/stack-azure.yaml
Prep docs and references for v0.8.0 release.
*Note: docs links will be picked up and generated automatically after tag*
I have:
=> [release-0.8] Prep docs and references for v0.8.0 release

apis/cache/v1beta1/redis_types.go, apis/database/v1beta1/sql_types.go, config/crd/cache.azure.crossplane.io_redis.yaml, config/crd/database.azure.crossplane.io_mysqlservers.yaml, config/crd/database.azure.crossplane.io_postgresqlservers.yaml, go.sum
Currently some of the printer columns on cache and database types do not point to valid fields in the status of the resources. This updates them to point to valid ones.
Thanks @artursouza for catching :+1: 
I have:
=> Fix printer columns on v1beta1 resources

apis/cache/v1beta1/redis_types.go, apis/compute/v1alpha3/types.go, apis/database/v1alpha3/nosql_types.go, apis/database/v1alpha3/virtualnetworkrule.go, apis/database/v1beta1/sql_types.go, apis/network/v1alpha3/types.go, apis/storage/v1alpha3/types.go, apis/v1alpha3/types.go, config/crd/azure.crossplane.io_providers.yaml, config/crd/azure.crossplane.io_resourcegroups.yaml, config/crd/cache.azure.crossplane.io_redis.yaml, config/crd/cache.azure.crossplane.io_redisclasses.yaml, config/crd/compute.azure.crossplane.io_aksclusterclasses.yaml, config/crd/compute.azure.crossplane.io_aksclusters.yaml, config/crd/database.azure.crossplane.io_cosmosdbaccounts.yaml, config/crd/database.azure.crossplane.io_mysqlservers.yaml, config/crd/database.azure.crossplane.io_mysqlservervirtualnetworkrules.yaml, config/crd/database.azure.crossplane.io_postgresqlservers.yaml, config/crd/database.azure.crossplane.io_postgresqlservervirtualnetworkrules.yaml, config/crd/database.azure.crossplane.io_sqlserverclasses.yaml, config/crd/network.azure.crossplane.io_subnets.yaml, config/crd/network.azure.crossplane.io_virtualnetworks.yaml, config/crd/storage.azure.crossplane.io_accounts.yaml, config/crd/storage.azure.crossplane.io_containerclasses.yaml, config/crd/storage.azure.crossplane.io_containers.yaml
These categories allow for instances of provider-azure CRDs to be group listed. The added categories are as follows:
Manged Resources: crossplane, managed, azure
Classes: crossplane, class, azure
Provider: crossplane, provider, azure
Ref: crossplane/provider-gcp#215
I have:
=> Add categories to all CRDs

cluster/local/integration_tests.sh, config/stack/manifests/resources/accountclass.resource.yaml, config/stack/manifests/resources/aksclusterclass.resource.yaml, config/stack/manifests/resources/containerclass.resource.yaml, config/stack/manifests/resources/redisclass.resource.yaml, config/stack/manifests/resources/sqlserverclass.resource.yaml, config/stack/samples/install.stack.yaml, examples/stack-azure.yaml
Prep docs and references for v0.9.0 release
I have:
=> [release-0.9] Prep docs and references for v0.9.0 release

apis/cache/v1beta1/redis_types.go, apis/compute/v1alpha3/types.go, apis/database/v1alpha3/firewallrule.go, apis/database/v1alpha3/nosql_types.go, apis/database/v1alpha3/virtualnetworkrule.go, apis/database/v1beta1/sql_types.go, apis/network/v1alpha3/types.go, apis/storage/v1alpha3/types.go, config/crd/cache.azure.crossplane.io_redis.yaml, config/crd/compute.azure.crossplane.io_aksclusters.yaml, config/crd/database.azure.crossplane.io_cosmosdbaccounts.yaml, config/crd/database.azure.crossplane.io_mysqlserverfirewallrules.yaml, config/crd/database.azure.crossplane.io_mysqlservers.yaml, config/crd/database.azure.crossplane.io_mysqlservervirtualnetworkrules.yaml, config/crd/database.azure.crossplane.io_postgresqlservers.yaml, config/crd/network.azure.crossplane.io_virtualnetworks.yaml, config/crd/storage.azure.crossplane.io_containers.yaml
Signed-off-by: Muvaffak Onus <onus.muvaffak@gmail.com>
They were missing in some of the resources.
I have:
=> Add Ready and Synced printer columns to all resources

apis/v1alpha3/types.go, config/crd/azure.crossplane.io_resourcegroups.yaml
API returns error if location is not given:
```
'create failed: cannot create ResourceGroup: resources.GroupsClient#CreateOrUpdate:
Invalid input: autorest/validation: validation failed: parameter=parameters.Location
constraint=Null value=(*string)(nil) details: value can not be null; required
parameter'
```
I have:
=> Location field of ResourceGroup is required

go.mod, go.sum
This PR updates go modules for crossplane-runtime v0.9.0 and crossplane v0.11.0, in prep for the v0.10. release of this provider
I have:
=> update go modules for crossplane-runtime v0.9.0 and crossplane v0.11.0

cluster/local/integration_tests.sh, config/package/manifests/resources/accountclass.resource.yaml, config/package/manifests/resources/aksclusterclass.resource.yaml, config/package/manifests/resources/containerclass.resource.yaml, config/package/manifests/resources/redisclass.resource.yaml, config/package/manifests/resources/sqlserverclass.resource.yaml, examples/provider-azure.yaml
This PR updates docs, examples, integration tests to v0.10.0 in prep of that release.
I have:
=> pin versions to v0.10.0

cluster/local/integration_tests.sh, config/package/manifests/resources/aksclusterclass.resource.yaml, config/package/manifests/resources/containerclass.resource.yaml, config/package/manifests/resources/redisclass.resource.yaml, config/package/manifests/resources/sqlserverclass.resource.yaml, config/package/samples/install.package.yaml, examples/provider-azure.yaml
Prep docs and references for v0.11.0 release
I have:
=> [release-0.11] Prep docs and references for v0.11.0 release

apis/database/v1alpha3/firewallrule.go, apis/database/v1alpha3/virtualnetworkrule.go, config/crd/database.azure.crossplane.io_postgresqlserverfirewallrules.yaml, config/crd/database.azure.crossplane.io_postgresqlservervirtualnetworkrules.yaml
Looks like these resources are missing ready and synced printer columns.
I have:
=> Missing printer columns

pkg/clients/azure_test.go
Removes an extraneous print statement that was unintentionally left
behind.
I have:
=> Remove extraneous print statement from test

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/golangci-lint.yml, pkg/clients/database/cosmosdb/account.go, pkg/controller/database/postgresqlserver/managed.go, pkg/controller/storage/account/account.go
Updates PR and issue templates as well as GitHub workflows and build submodule to match crossplane/crossplane#1775.
I have:
=> Match crossplane/crossplane build and GitHub configuration

cluster/images/provider-azure/Dockerfile, cluster/images/provider-azure/Makefile, cluster/local/integration_tests.sh
Updates the provider package image to only include a single static
package.yaml file that can be parsed by the package manager.
Signed-off-by: hasheddan georgedanielmangum@gmail.com
I have:
See https://github.com/crossplane/provider-aws/pull/365 and https://github.com/crossplane/crossplane/issues/1756 for more info.
=> Build provider packages with static content

apis/v1beta1/zz_generated.pc.go, go.mod, go.sum, package/crds/azure.crossplane.io_providerconfigs.yaml, pkg/clients/azure.go
See https://github.com/crossplane/crossplane-runtime/pull/212 for context. 
I have:
I've run through the `docs/snippets/compose` example for Azure.
=> Use distinct ProviderConfig credentials field

examples/cache/redis.yaml
I noticed while investigating https://github.com/crossplane/provider-azure/issues/204 that our Redis example was broken.
I have:
By running `kubectl apply -f redis.yaml` and observing the cache come up.
=> Fix Redis example

INSTALL.md
Signed-off-by: Robert Collins <robert.collins@cognite.com>
I hit a roadbump getting started, and it isn't covered in 'make help', so I thought I'd document it for other new contributors.
Fixes #211
I have:
- [X ] Read and followed Crossplane's [contribution process].
- [ X] Run `make reviewable test` to ensure this PR is ready for review.
=> Document how to build with new golang versions

apis/database/v1beta1/sql_types.go, examples/database/mysqlserver.yaml, examples/database/postgresqlserver.yaml, package/crds/database.azure.crossplane.io_mysqlservers.yaml, package/crds/database.azure.crossplane.io_postgresqlservers.yaml, pkg/clients/database/mysql.go, pkg/clients/database/postgresql.go
Signed-off-by: Robert Collins <robert.collins@cognite.com>
Fixes #210 
I have:
- [X ] Read and followed Crossplane's [contribution process].
- [ X] Run `make reviewable test` to ensure this PR is ready for review.
I have not run this against Azure yet, as I'm not sure of the mechanism to plug this custom controller into a running cluster etc - thats marked  "TBD: Steps to install the Azure provider into a Crossplane cluster" in `INSTALL.MD`.
=> Support minimalTlsVersion on DBs: Fixes #210

INSTALL.md, examples/database/mysqlserver.yaml, examples/database/postgresqlserver.yaml, examples/storage/container.yaml
Just some misc changes, some promised, some discovered during manual testing. All should be self evident.
- [x ] Read and followed Crossplane's [contribution process].
- [ x] Run `make reviewable test` to ensure this PR is ready for review.
Manualiiiiie
=> Fix examples and link to Crossplane contributing guide

INSTALL.md, Makefile
Add instructions to run provider locally.
Fix path to binary in Makefile. It's also hardcoded in provider-aws.
Copied from https://github.com/crossplane/provider-aws/blob/master/INSTALL.md#run
I have:
Tried it locally in Kind.
=> Update instructions to run provider locally

apis/database/v1beta1/sql_types.go, pkg/controller/database/postgresqlserver/managed.go, pkg/controller/database/postgresqlserver/managed_test.go
Fixes https://github.com/crossplane/provider-azure/issues/224
I have:
Unit test.
=> postgresqlserver: add the constant port to connection details secret

go.mod, go.sum
Updates crossplane-runtime dependency to v0.13.0.
I have:
`make build`
=> Update crossplane-runtime to v0.13.0

cluster/local/integration_tests.sh, go.mod, go.sum
Update build submodule and crossplane-tools before the release.
I have:
N/A
=> Update build submodule and crossplane-tools

package/crossplane.yaml
Per crossplane/crossplane#2299 , we'd like to have a patch release of providers to expose that metadata.
I have:
N/A
=> Backport new package metadata format to 0.16

examples/compute/akscluster.yaml
compute.akscluster: updated version to an available one in that region
I have:
Manually. It still failed in the end due to another problem but at least creation call was made.
=> compute.akscluster: updated version to an available one in that region

cluster/local/integration_tests.sh
Equivalent of https://github.com/crossplane/provider-aws/pull/711
I have:
GH Action
=> e2e: update integration test script

pkg/clients/database/mysql.go, pkg/clients/database/mysql_test.go
Make `spec.forProvider.publicNetworkAccess` effective 
Fixes #294
I have:
=> [MySQLServer] Make forProvider.publicNetworkAccess effective

cluster/local/integration_tests.sh
Signed-off-by: haarchri <chhaar30@googlemail.com>
fixed e2e-test in provider-aws after https://github.com/crossplane/crossplane/pull/2804
you can see here that the e2e-test is failing: 
https://github.com/crossplane/provider-aws/runs/4716896964?check_suite_focus=true#step:12:79
Fixes #
I have:
=> fix(e2e-test) changed pkg.crossplane.io to v1
